name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [master]

env:
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - run: npm run lint
      - run: npm run build
      - name: docker login
        run: | # log into docker hub account
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
      - name: Get current date # get the date of the build
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
      - name: Build the Docker image # push The image to the docker hub
        run: docker build . --file Dockerfile --tag consensys/quorum-explorer:${{ steps.date.outputs.date }}
      - name: Docker Push
        run: docker push consensys/quorum-explorer:${{ steps.date.outputs.date }}